const commentSeeds = [
  {
    comment: 'Bruh! What does this mean? I think you need a title thatbetter suits the writing',
    anchorKey: 'cqvfr',
    anchorOffset: 70,
    focusKey: 'cqvfr',
    focusOffset: 11,
    isBackward: true,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 4,
    DocumentId: 1
  },
  {
    comment: 'Great sentence',
    anchorKey: '41dmf',
    anchorOffset: 441,
    focusKey: '41dmf',
    focusOffset: 592,
    isBackward: false,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 4,
    DocumentId: 1
  },
  {
    comment: 'You mispelled this word, i believe you mean \'present\'',
    anchorKey: '41dmf',
    anchorOffset: 1633,
    focusKey: '41dmf',
    focusOffset: 1625,
    isBackward: true,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 4,
    DocumentId: 1
  },
  {
    comment: 'I believe you should expand on this. Give more details',
    anchorKey: '8d69b',
    anchorOffset: 4,
    focusKey: '8d69b',
    focusOffset: 346,
    isBackward: false,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 4,
    DocumentId: 1
  },
  {
    comment: 'Now this is an ending worth my cereal!',
    anchorKey: '10gda',
    anchorOffset: 0,
    focusKey: '10gda',
    focusOffset: 1492,
    isBackward: false,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 4,
    DocumentId: 1
  },
  {
    comment: 'This needs to be centered',
    anchorKey: '89fhq',
    anchorOffset: 45,
    focusKey: '89fhq',
    focusOffset: 73,
    isBackward: false,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 1,
    DocumentId: 1
  },
  {
    comment: 'You mispelled present',
    anchorKey: '41dmf',
    anchorOffset: 1625,
    focusKey: '41dmf',
    focusOffset: 1633,
    isBackward: false,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 1,
    DocumentId: 1
  },
  {
    comment: 'This needs to be centered',
    anchorKey: 'cf801',
    anchorOffset: 70,
    focusKey: 'cf801',
    focusOffset: 48,
    isBackward: true,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 1,
    DocumentId: 1
  },
  {
    comment: 'This sentence does add any value to the paragraph',
    anchorKey: 'bl3d6',
    anchorOffset: 958,
    focusKey: 'bl3d6',
    focusOffset: 1118,
    isBackward: false,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 1,
    DocumentId: 1
  },
  {
    comment: 'This needs to be centered',
    anchorKey: '73f6g',
    anchorOffset: 73,
    focusKey: '73f6g',
    focusOffset: 32,
    isBackward: true,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 1,
    DocumentId: 1
  },
  {
    comment: 'This needs to be centered',
    anchorKey: '9ou1n',
    anchorOffset: 70,
    focusKey: '9ou1n',
    focusOffset: 64,
    isBackward: true,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 1,
    DocumentId: 1
  },
  {
    comment: 'Yasss! great conclusion!!',
    anchorKey: '10gda',
    anchorOffset: 0,
    focusKey: '10gda',
    focusOffset: 1492,
    isBackward: false,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 1,
    DocumentId: 1
  }
]

module.exports = commentSeeds;
