const commentSeeds = [
  {
    comment: 'Bruh! What does this mean? I think you need a title that better suits the writing',
    anchorKey: 'cqvfr',
    anchorOffset: 70,
    focusKey: 'cqvfr',
    focusOffset: 11,
    isBackward: true,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 4,
    DocumentId: 1
  },
  {
    comment: 'Great sentence',
    anchorKey: '41dmf',
    anchorOffset: 441,
    focusKey: '41dmf',
    focusOffset: 592,
    isBackward: false,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 4,
    DocumentId: 1
  },
  {
    comment: 'You mispelled this word, i believe you mean \'present\'',
    anchorKey: '41dmf',
    anchorOffset: 1633,
    focusKey: '41dmf',
    focusOffset: 1625,
    isBackward: true,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 4,
    DocumentId: 1
  },
  {
    comment: 'I believe you should expand on this. Give more details',
    anchorKey: '8d69b',
    anchorOffset: 4,
    focusKey: '8d69b',
    focusOffset: 346,
    isBackward: false,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 4,
    DocumentId: 1
  },
  {
    comment: 'Now this is an ending worth my cereal!',
    anchorKey: '10gda',
    anchorOffset: 0,
    focusKey: '10gda',
    focusOffset: 1492,
    isBackward: false,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 4,
    DocumentId: 1
  },
  {
    comment: 'This needs to be centered',
    anchorKey: '89fhq',
    anchorOffset: 45,
    focusKey: '89fhq',
    focusOffset: 73,
    isBackward: false,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 1,
    DocumentId: 1
  },
  {
    comment: 'You mispelled present',
    anchorKey: '41dmf',
    anchorOffset: 1625,
    focusKey: '41dmf',
    focusOffset: 1633,
    isBackward: false,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 1,
    DocumentId: 1
  },
  {
    comment: 'This needs to be centered',
    anchorKey: 'cf801',
    anchorOffset: 70,
    focusKey: 'cf801',
    focusOffset: 48,
    isBackward: true,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 1,
    DocumentId: 1
  },
  {
    comment: 'This sentence does add any value to the paragraph',
    anchorKey: 'bl3d6',
    anchorOffset: 958,
    focusKey: 'bl3d6',
    focusOffset: 1118,
    isBackward: false,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 1,
    DocumentId: 1
  },
  {
    comment: 'This needs to be centered',
    anchorKey: '73f6g',
    anchorOffset: 73,
    focusKey: '73f6g',
    focusOffset: 32,
    isBackward: true,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 1,
    DocumentId: 1
  },
  {
    comment: 'This needs to be centered',
    anchorKey: '9ou1n',
    anchorOffset: 70,
    focusKey: '9ou1n',
    focusOffset: 64,
    isBackward: true,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 1,
    DocumentId: 1
  },
  {
    comment: 'Yasss! great conclusion!!',
    anchorKey: '10gda',
    anchorOffset: 0,
    focusKey: '10gda',
    focusOffset: 1492,
    isBackward: false,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 1,
    DocumentId: 1
  },
  {
    comment: "It's spelled catch.",
    anchorKey: 'e41v3',
    anchorOffset: 218,
    focusKey: 'e41v3',
    focusOffset: 223,
    isBackward: false,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 2,
    DocumentId: 5
  },
  {
    comment: "It's spelled memory.",
    anchorKey: '308a8',
    anchorOffset: 384,
    focusKey: '308a8',
    focusOffset: 389,
    isBackward: false,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 2,
    DocumentId: 5
  },
  {
    comment: 'This is not a good transition.',
    anchorKey: '8mqeh',
    anchorOffset: 123,
    focusKey: '8mqeh',
    focusOffset: 149,
    isBackward: false,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 2,
    DocumentId: 5
  },
  {
    comment: 'Maybe you can reference the lyrics without literally including them? ',
    anchorKey: 'cmrm7',
    anchorOffset: 0,
    focusKey: 'cmrm7',
    focusOffset: 24,
    isBackward: false,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 1,
    DocumentId: 5
  },
  {
    comment: 'What is poke-legacy? Please elaborate more.',
    anchorKey: 'e41v3',
    anchorOffset: 185,
    focusKey: 'e41v3',
    focusOffset: 196,
    isBackward: false,
    hasFocus: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    UserId: 1,
    DocumentId: 5
  }
];

module.exports = commentSeeds;
